# Generated by Django 3.2 on 2021-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlsEncurtadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField(verbose_name='URL Original')),
                ('url_encurtada_sugestao', models.URLField(blank=True, null=True, unique=True, verbose_name='Sugestão de URL')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name_plural': 'URLS Encurtadas',
            },
        ),
    ]
