# Generated by Django 3.2 on 2021-04-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtadorLink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsencurtadas',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expiracao'),
        ),
        migrations.AlterField(
            model_name='urlsencurtadas',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='urlsencurtadas',
            name='url_encurtada_sugestao',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='URL Encurtada'),
        ),
        migrations.AlterField(
            model_name='urlsencurtadas',
            name='url_original',
            field=models.URLField(unique=True, verbose_name='URL Original'),
        ),
    ]
