# Generated by Django 3.2 on 2021-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtadorLink', '0002_auto_20210425_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsencurtadas',
            name='data_expiracao',
            field=models.DateField(blank=True, default=1, verbose_name='Data de Expiracao'),
            preserve_default=False,
        ),
    ]
