# Generated by Django 3.2 on 2021-04-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtadorLink', '0002_alter_urlsencurtadas_url_encurtada_sugestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsencurtadas',
            name='url_original',
            field=models.URLField(unique=True, verbose_name='URL Original'),
        ),
    ]
