# Generated by Django 3.2 on 2021-04-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtadorLink', '0007_alter_urlsencurtadas_url_encurtada_sugestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsencurtadas',
            name='url_encurtada_sugestao',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='http://tiag.o/'),
        ),
    ]
