# Generated by Django 3.2 on 2021-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtadorLink', '0008_alter_urlsencurtadas_url_encurtada_sugestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsencurtadas',
            name='url_encurtada_sugestao',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='URL Encurtada'),
        ),
    ]
