# Generated by Django 3.2 on 2021-04-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtadorLink', '0009_alter_urlsencurtadas_url_encurtada_sugestao'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsencurtadas',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expiracao'),
        ),
    ]
