# Generated by Django 3.2 on 2021-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtadorLink', '0009_alter_urlsencurtadas_url_encurtada_sugestao'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsencurtadas',
            name='data_expiracao',
            field=models.DateField(default=1, verbose_name='Data de Expiracao'),
            preserve_default=False,
        ),
    ]
