# Generated by Django 3.2 on 2021-04-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtadorLink', '0010_urlsencurtadas_data_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsencurtadas',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
